### ISSUE TITLE
Jenkins failures don't always fail build

### ISSUE THREAD

**Issue by andschwa** [Microsoft/openenclave#1237] opened 2018-12-20 20:30 UTC
I think I found a bug [here](https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/staging/372/pipeline/19) where the "Check Pre-Commit Requirements" stage _should_ have failed, but did not:

```
[Bors_staging-SAVQQOGG4TMIJW6ZHSGG2MHERTL45R6RNECLBYNXEIQ6O4GKH54Q] Running shell script

+ ./scripts/check-precommit-reqs

Cannot contact Ubuntu-1604-1: java.lang.InterruptedException
```

That "Cannot contact" error I think ought to have failed that stage, and thus the whole build, but instead, everything passed.

/cc @johnkord @ionutbalutoiu

**Comment by oprinmarius** [comment] 2019-01-03 17:15
I searched other builds to see if this problem occurred somewhere else , but I couldn't find any.

This error usually occurs when there is a connection loss between the Jenkins master and the slave.
According to the comments from the following issues , this error often occurs when the Jenkins server is under high load

https://issues.jenkins-ci.org/browse/JENKINS-43038
https://issues.jenkins-ci.org/browse/JENKINS-52125
https://issues.jenkins-ci.org/browse/JENKINS-46853

**Comment by ionutbalutoiu** [comment] 2019-01-03 17:42
@andschwa We haven't actually seen this reproduced since then. It seems to be a corner case.

The most we could do is increase some timeout (if there's any) for Jenkins master <-> slave communication.

If that works for you, we can close this issue for now.

**Comment by johnkord** [comment] 2019-01-03 22:18
This is Andy, John explained to me that we split the 16 core node into two 8 core nodes which has drastically reduced the changes of this happening, so I am happy to close.

**Closed by johnkord** 2019-01-03 22:18 UTC
Labels: bug, ci/cd
