### ISSUE TITLE
oe-gdb often does not display symbols

### ISSUE THREAD

**Issue by achamayou** [Microsoft/openenclave#581] opened 2018-08-23 14:45 UTC
```
Illustration below, on a program started inside oe-gdb. When attaching (oe-gdb -p) or loading core files (oe-gdb -c), we never see any symbols. This makes debugging quite difficult.

$ objdump --debugging coco | wc -l                                                                                       
420375
$ objdump --debugging libsimplebank.signed.so 2>/dev/null | wc -l
5246662

$ /opt/openenclave/bin/oe-gdb ./coco
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Source directories searched: /opt/openenclave/lib/openenclave/debugger/gdb-sgx-plugin:$cdir:$cwd
No symbol table is loaded.  Use the "file" command.
No symbol table is loaded.  Use the "file" command.
No symbol table is loaded.  Use the "file" command.
Setting environment variable "LD_PRELOAD" to null value.
Reading symbols from ./coco...done.
(gdb) set args libsimplebank.signed.so raftelectiontimeout=100000 rafthost=127.243.6.62 raftport=36735 tlshost=127.243.6.62 tlsport=37750 log=0.log nodecert=0.pem enclavetype=simulate raftloglevel=4 
(gdb) run
Starting program: /tmp/v-amcham_0/coco libsimplebank.signed.so raftelectiontimeout=100000 rafthost=127.243.6.62 raftport=36735 tlshost=127.243.6.62 tlsport=37750 log=0.log nodecert=0.pem enclavetype=simulate raftloglevel=4 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff5e9c700 (LWP 9893)]
[New Thread 0x7ffff569b700 (LWP 9894)]
[New Thread 0x7ffff4e9a700 (LWP 9895)]
[New Thread 0x7ffff4699700 (LWP 9896)]
[New Thread 0x7ffff3e98700 (LWP 9897)]
[i]Starting new node.
[~]Creating new node.
[i]tls server bound to 127.243.6.62:37750
[i]raft server bound to 127.243.6.62:36735
[~]Receiving new TLS connection.
[~]new TLS connection: 140736956926040
[~]tls in: 140736956926040, size 399

Thread 1 "coco" received signal SIGSEGV, Segmentation fault.
0x00007fffe0286c71 in ?? ()
(gdb) bt
#0  0x00007fffe0286c71 in ?? ()
#1  0x00000020e0510c30 in ?? ()
#2  0x00007fffe052cbd8 in ?? ()
#3  0x00007fffe027833b in ?? ()
#4  0x00007fffe0278475 in ?? ()
#5  0x00007fffe0282afb in ?? ()
#6  0x00007fffe0268ad3 in ?? ()
#7  0x00007fffe0220a49 in ?? ()
#8  0x00007fffe0222d96 in ?? ()
#9  0x00007fffe02269e8 in ?? ()
#10 0x00007fffe0217b17 in ?? ()
#11 0x00007fffe0217b83 in ?? ()
#12 0x00007fffe0098190 in ?? ()
#13 0xa9f86694cbd3ddd2 in ?? ()
#14 0xffffffffffffffff in ?? ()
#15 0x0000000000000018 in ?? ()
#16 0x00007fffe052cb88 in ?? ()
#17 0x00007fffe052ca50 in ?? ()
#18 0x00007fffe052cba0 in ?? ()
#19 0x00007fffe892b860 in ?? ()
#20 0x00007fffe027849c in ?? ()
#21 0x0000000000000018 in ?? ()
#22 0x0000000000000001 in ?? ()
#23 0x00007fffe052cb88 in ?? ()
#24 0x0000000000000018 in ?? ()
#25 0x00007fffe892b890 in ?? ()
#26 0x00007fffe0282afb in ?? ()
#27 0x0000000000000018 in ?? ()
#28 0x0000000000000000 in ?? ()
```

**Comment by anakrish** [comment] 2018-12-27 18:00
The log for this issue indicates that the issue could have been observed with simulation mode:

(gdb) set args libsimplebank.signed.so raftelectiontimeout=100000 rafthost=127.243.6.62 raftport=36735 tlshost=127.243.6.62 tlsport=37750 log=0.log nodecert=0.pem ** enclavetype=simulate** raftloglevel=4 

Originally oe-gdb did not support simulation. 
Support for simulation mode was added in #1099 

In release mode, we are not able to reproduce this issue at all.
Closing this.

Feel free to create a new issue if you encounter this again.

**Closed by anakrish** 2018-12-27 18:00 UTC
Labels: bug, devtools
