### ISSUE TITLE
Sporadic failures in crypto tests

### ISSUE THREAD

**Issue by anakrish** [Microsoft/openenclave#1203] opened 2018-12-12 23:31 UTC
Crypto tests now generate data on the fly and sometimes this causes failures.

For example since the data in a generated certificate could be different from the timestamp of the certificate file itself, (say off by a second), the following test fails:

=== begin _test_get_dates()

Test failed: /home/jenkins/workspace/Bors_staging-SAVQQOGG4TMIJW6ZHSGG2MHERTL45R6RNECLBYNXEIQ6O4GKH54Q/tests/crypto/crl_tests.c(144): _test_get_dates last.seconds == _time.seconds

https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/staging/339/pipeline

**Comment by ionutbalutoiu** [comment] 2019-03-01 14:40
This looks to be consistently reproduced now. So far, I noticed the following CI runs with all the testing stages failing:

* [OpenEnclave-nightly_packages/211](https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/OpenEnclave-nightly_packages/detail/OpenEnclave-nightly_packages/211/pipeline)
* [OpenEnclave-libcxx_tests/215](https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/OpenEnclave-libcxx_tests/detail/OpenEnclave-libcxx_tests/215/pipeline)

giving:
```
81 - tests/crypto/enclave (Failed)
82 - tests/crypto/host (Child aborted)
```

CC: @johnkord @andschwa @anitagov

**Comment by aserdean** [comment] 2019-03-01 14:42
Bump on the failure:
```
Test failed: ../tests/crypto/crl_tests.c(150): _test_get_dates next.month == _time.month
```
It reproduced because of the month now, see [here](
https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/OpenEnclave-sandbox/detail/OpenEnclave-sandbox/784/pipeline#log-536) and [here (over the entire Linux stages)](https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/OpenEnclave-sandbox/detail/OpenEnclave-sandbox/785/pipeline#step-894-log-523)

**Comment by johnkord** [comment] 2019-03-01 18:13
Interesting, I'll try to investigate this today! Thanks. I think this is just an edge case during month rollover in our tests, but I'm not sure if it affects anything more important.

**Comment by johnkord** [comment] 2019-03-01 19:00
This appears to be related to next year being a leap year!

Here is the CRL that is generated:
```
azureuser@accVM:~/openenclave/build/tests/crypto$ openssl crl -in ../../../build/tests/crypto/data/intermediate_crl.der -inform DER -text -noout
Certificate Revocation List (CRL):
        Version 2 (0x1)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: /C=US/ST=Ohio/L=Columbus/O=Acme Company/OU=Acme/CN=Intermediate
        Last Update: Mar  1 18:33:07 2019 GMT
        Next Update: Feb 29 18:33:07 2020 GMT
        CRL extensions:
            X509v3 CRL Number:
                1
Revoked Certificates:
    Serial Number: B2F0584DDC28BC1C
        Revocation Date: Mar  1 18:33:07 2019 GMT
    Signature Algorithm: sha256WithRSAEncryption
         29:86:81:96:82:dc:4b:39:4b:f2:99:15:2f:21:4f:88:9f:32:
         41:ae:18:a5:84:7f:49:5b:1c:dc:a2:f4:ac:d5:da:09:4e:04:
         0c:dc:6c:ee:d9:7a:60:9b:4a:a7:c9:43:7d:be:97:30:da:dc:
         99:07:1a:30:00:62:e7:77:62:d7:f8:7f:f4:13:72:44:f1:d7:
         3a:14:33:95:f0:d6:f2:99:9f:38:7b:40:5d:79:26:83:bc:35:
         66:17:3e:66:c4:c1:0f:74:f4:e7:4b:67:bf:c6:c5:85:58:bf:
         d1:70:eb:95:91:c3:66:ef:03:89:ab:d2:5d:04:21:e5:34:62:
         ab:f8:b8:62:0c:bd:19:90:d8:41:d4:18:d0:61:52:58:f9:65:
         24:06:36:72:6a:c9:19:63:eb:1d:00:4e:42:4b:73:98:34:0c:
         c0:e1:40:3e:ca:dd:ed:bf:76:1f:6e:97:7b:1c:62:55:ed:54:
         5e:00:49:5b:4d:16:92:b4:e3:af:02:6d:11:bc:06:5d:4b:37:
         73:7b:a0:1d:ee:3d:b8:66:29:04:86:2d:5c:de:64:1b:22:72:
         f8:47:d7:40:15:e7:67:c8:01:a2:ed:fd:3a:40:0e:20:ee:12:
         5f:5b:a4:d1:21:88:f8:a9:da:ba:c4:d4:a3:32:73:9c:c6:b5:
         61:b8:f2:2b
```

This CRL (intermediate_crl.der/pem) is created to have a 365 day expiration time (specified in tests/crypto/data/intermediate.cnf). This means that today (March 1st), the month won't match the month from the expected month in the "Next" field in the generated CRL, which you can see above in the generated CRL data: `Next Update: Feb 29 18:33:07 2020 GMT`.

Tomorrow, the month will begin to match again, but the day won't match, so these tests will continue to fail. The day won't match for a year until we pass the next leap year day (Feb 29th, 2020), so this needs to be fixed in these tests or our CI will continuously fail

**Comment by johnkord** [comment] 2019-03-01 19:17
Tagging @soccerGB @anakrish because I've heard that you both were discussing this issue you hit last night!

**Comment by andschwa** [comment] 2019-03-01 19:42
@johnkord That's hilarious! I just ran saw this errors on my PR too, ah leap years! It's funny that one of the hardest thing to do with computers is to count time 🤣

**Comment by johnkord** [comment] 2019-03-01 19:46
It's so true. And dealing with time zones is a huge issue, because it involves so much: politics, locales, publishing/distribution, updates, daylight savings time, etc. I've hit at least one issue in basically every project I've ever worked on because of something related to datetime. Anyway, I'm looking into a fix for this.

**Comment by johnkord** [comment] 2019-03-01 23:41
This should be fixed now @ionutbalutoiu @aserdean

**Comment by aserdean** [comment] 2019-03-07 11:47
Unfortunately bump on this one again:
```
Test failed: ../tests/crypto/crl_tests.c(151): _test_get_dates next.day == _time.day
```
you can see it across the run [here](https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/OpenEnclave-sandbox/detail/OpenEnclave-sandbox/823/pipeline/#step-855-log-523)

CC: @johnkord @andschwa @ionutbalutoiu

**Comment by johnkord** [comment] 2019-03-07 17:46
@johnkord Remove the "temporary" comment in the file associated with this test

**Closed** 2019-03-07 17:46 UTC
Labels: testing
