### ISSUE TITLE
CMake: Each test enclave needs to use add_enclave_executable

### ISSUE THREAD

**Issue by anakrish** [Microsoft/openenclave#1163] opened 2018-12-05 00:35 UTC
Today most of the test enclaves are not signed. They include add_enclave_executable.cmake, but don't actually call the add_enclave_executable function since add_enclave_executable performs signing.

The add_enclave_executable function needs to be flexible enough so that the test enclaves can opt out of signing. If all the test enclaves were using add_enclave_executable, then the add_enclave_executable can internally do the right things for build ELF enclaves on Windows.

CC: @soccerGB @andschwa

**Comment by andschwa** [comment] 2018-12-05 18:49
I am closing this as a duplicate of #891 (which is in progress; @radhikaj has a branch cleaning this up but was pulled away to Protobuf stuff).

**Closed by andschwa** 2018-12-05 18:49 UTC
Labels: build, windows
