### ISSUE TITLE
Investigate why the crypto/enclave test is failing now on Windows.

### ISSUE THREAD

**Issue by johnkord** [microsoft/openenclave#1927] opened 2019-06-12 21:19 UTC
The crypto test will be temporarily disabled to unblock CI in PR #1926 

We need to investigate why this test began failing. I believe some new Ansible changes were pushed to the Windows CI systems. @ionutbalutoiu can give some more context, and @anitagov has some context as well.

**Comment by johnkord** [comment] 2019-06-13 01:03
Here's an example of one of the CI failures:
https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/staging/942/pipeline

```
Start  82: tests/crypto/enclave

82: Test command: D:\Jenkins\workspace\Bors_staging\build\X64-Debug\tests\crypto\enclave\host\cryptohost.exe "D:/Jenkins/workspace/Bors_staging/build/X64-Debug/tests/crypto/enclave/enc/cryptoenc"
82: Test timeout computed to be: 480
82: === begin _test_asn1_parsing()
82: str=SEQUENCE: length=1c1
82:     SEQUENCE: length=1e
82:         OID: 1.2.840.113741.1.13.1.1
82:         OCTET_STRING:
82:             length=10
82:             data=1f8c1e7ba6bd107d8424dd35649dcd72
82:     SEQUENCE: length=164
82:         OID: 1.2.840.113741.1.13.1.2
82:         SEQUENCE: length=154
82:             SEQUENCE: length=10
82:                 OID: 1.2.840.113741.1.13.1.2.1
82:                 INTEGER: value=4
82:             SEQUENCE: length=10
82:                 OID: 1.2.840.113741.1.13.1.2.2
82:                 INTEGER: value=4
82:             SEQUENCE: length=10
82:                 OID: 1.2.840.113741.1.13.1.2.3
82:                 INTEGER: value=2
82:             SEQUENCE: length=10
82:                 OID: 1.2.840.113741.1.13.1.2.4
82:                 INTEGER: value=4
82:             SEQUENCE: length=10
82:                 OID: 1.2.840.113741.1.13.1.2.5
82:                 INTEGER: value=1
82:             SEQUENCE: length=11
82:                 OID: 1.2.840.113741.1.13.1.2.6
82:                 INTEGER: value=128
82:             SEQUENCE: length=10
82:                 OID: 1.2.840.113741.1.13.1.2.7
82:                 INTEGER: value=0
82:             SEQUENCE: length=10
82:                 OID: 1.2.840.113741.1.13.1.2.8
82:                 INTEGER: value=0
82:             SEQUENCE: length=10
82:                 OID: 1.2.840.113741.1.13.1.2.9
82:                 INTEGER: value=0
82:             SEQUENCE: length=10
82:                 OID: 1.2.840.113741.1.13.1.2.10
82:                 INTEGER: value=0
82:             SEQUENCE: length=10
82:                 OID: 1.2.840.113741.1.13.1.2.11
82:                 INTEGER: value=0
82:             SEQUENCE: length=10
82:                 OID: 1.2.840.113741.1.13.1.2.12
82:                 INTEGER: value=0
82:             SEQUENCE: length=10
82:                 OID: 1.2.840.113741.1.13.1.2.13
82:                 INTEGER: value=0
82:             SEQUENCE: length=10
82:                 OID: 1.2.840.113741.1.13.1.2.14
82:                 INTEGER: value=0
82:             SEQUENCE: length=10
82:                 OID: 1.2.840.113741.1.13.1.2.15
82:                 INTEGER: value=0
82:             SEQUENCE: length=10
82:                 OID: 1.2.840.113741.1.13.1.2.16
82:                 INTEGER: value=0
82:             SEQUENCE: length=10
82:                 OID: 1.2.840.113741.1.13.1.2.17
82:                 INTEGER: value=5
82:             SEQUENCE: length=1f
82:                 OID: 1.2.840.113741.1.13.1.2.18
82:                 OCTET_STRING:
82:                     length=10
82:                     data=04040204018000000000000000000000
82:     SEQUENCE: length=10
82:         OID: 1.2.840.113741.1.13.1.3
82:         OCTET_STRING:
82:             length=2
82:             data=0000
82:     SEQUENCE: length=14
82:         OID: 1.2.840.113741.1.13.1.4
82:         OCTET_STRING:
82:             length=6
82:             data=00906ea10000
82:     SEQUENCE: length=f
82:         OID: 1.2.840.113741.1.13.1.5
82:         UNKNOWN:
82:             tag=0a
82:             length=1
82:             data=00
82: 
82: === passed _test_asn1_parsing()
82: === begin _test_verify_without_crl()
82: === passed _test_verify_without_crl()
82: === begin _test_verify_without_crl()
82: === passed _test_verify_without_crl()
82: === begin _test_verify_with_crl()
82: === passed _test_verify_with_crl()
82: === begin _test_verify_with_two_crls()
82: === passed _test_verify_with_two_crls()
82: === begin _test_verify_with_two_crls()
82: === passed _test_verify_with_two_crls()
82: === begin _test_get_dates()
82: === passed _test_get_dates()
82: === begin _test_cert_extensions()
82: === passed _test_cert_extensions()
82: === begin _test_cert_extensions()
82: === passed _test_cert_extensions()
82: === begin _test_crl_distribution_points()
82: URL{https://certificates.trustedservices.intel.com/IntelSGXPCKProcessor.crl}
82: === passed _test_crl_distribution_points()
82: === begin _test_sign_and_verify()
82: === passed _test_sign_and_verify()
82: === begin _test_generate()
82: === passed _test_generate()
82: === begin _test_generate_from_private()
82: === passed _test_generate_from_private()
82: === begin _test_write_private()
82: === passed _test_write_private()
82: === begin _test_write_public()
82: Test failed: ..\..\tests\crypto\ec_tests.c(468): _test_write_public (strlen(_PUBLIC_KEY) + 1) == pem_size
82: : ..\..\tests\crypto\enclave\host\host.c(86): error: test() failed: result=19
82: 22:43:09:000000 tid(0x1428) (E)[ERROR]cryptoenc:mbedtls_x509_crt_verify failed with The certificate has been revoked (is on a CRL)
82:  (flags=0x2)
82:  (oe_result_t=OE_VERIFY_REVOKED)[..\..\enclave\crypto\cert.c _mbedtls_x509_crt_verify:348]
82: 22:43:09:000000 tid(0x1428) (E)[ERROR]cryptoenc::OE_VERIFY_REVOKED[..\..\enclave\crypto\cert.c oe_cert_verify:856]
82: 22:43:09:000000 tid(0x1428) (E)[ERROR]cryptoenc:mbedtls_x509_crt_verify failed with The certificate has been revoked (is on a CRL)
82:  (flags=0x2)
82:  (oe_result_t=OE_VERIFY_REVOKED)[..\..\enclave\crypto\cert.c _mbedtls_x509_crt_verify:348]
82: 22:43:09:000000 tid(0x1428) (E)[ERROR]cryptoenc::OE_VERIFY_REVOKED[..\..\enclave\crypto\cert.c oe_cert_verify:856]
82: 22:43:09:000000 tid(0x1428) (E)[ERROR]cryptoenc:mbedtls_x509_crt_verify failed with The certificate has been revoked (is on a CRL)
82:  (flags=0x2)
82:  (oe_result_t=OE_VERIFY_REVOKED)[..\..\enclave\crypto\cert.c _mbedtls_x509_crt_verify:348]
82: 22:43:09:000000 tid(0x1428) (E)[ERROR]cryptoenc::OE_VERIFY_REVOKED[..\..\enclave\crypto\cert.c oe_cert_verify:856]
82: 22:43:09:000000 tid(0x1428) (E)[ERROR]cryptoenc::OE_BUFFER_TOO_SMALL[..\..\common\cert.c oe_get_crl_distribution_points:201]
82: 22:43:09:000000 tid(0x1428) (E)[ERROR]cryptoenc::OE_BUFFER_TOO_SMALL[..\..\enclave\crypto\key.c oe_private_key_sign:382]
82: 22:43:09:000000 tid(0x1428) (E)[ERROR]cryptoenc::OE_BUFFER_TOO_SMALL[..\..\enclave\crypto\key.c oe_private_key_sign:382]
82: 22:43:09:000000 tid(0x1428) (E)[ERROR]cryptoenc::OE_BUFFER_TOO_SMALL[..\..\enclave\crypto\key.c oe_private_key_sign:382]
82: 22:43:09:000000 tid(0x1428) (E)[ERROR]cryptoenc::OE_BUFFER_TOO_SMALL[..\..\enclave\crypto\key.c oe_private_key_sign:382]
82: 22:43:09:000000 tid(0x1428) (E)[ERROR]cryptoenc:mbedtls error: 0xffffb380 (oe_result_t=OE_CRYPTO_ERROR)[..\..\enclave\crypto\ec.c oe_ec_generate_key_pair_from_private:361]
82: 22:43:09:000000 tid(0x1428) (E)[ERROR]cryptoenc:mbedtls error: 0xffffb380 (oe_result_t=OE_CRYPTO_ERROR)[..\..\enclave\crypto\ec.c oe_ec_generate_key_pair_from_private:361]
82: 22:43:09:000000 tid(0x1428) (E)[ERROR]cryptoenc::OE_BUFFER_TOO_SMALL[..\..\enclave\crypto\key.c oe_private_key_sign:382]
82: 22:43:09:000000 tid(0x1428) (E)[ERROR]cryptoenc::OE_BUFFER_TOO_SMALL[..\..\enclave\crypto\key.c oe_private_key_sign:382]
82: 22:43:09:000000 tid(0x1428) (E)[ERROR]cryptoenc:mbedtls_error = 0xffffb380[..\..\enclave\crypto\ec.c oe_ec_valid_raw_private_key:604]
82: 22:43:09:000000 tid(0x1428) (E)[ERROR]cryptoenc:mbedtls_error = 0xffffb380[..\..\enclave\crypto\ec.c oe_ec_valid_raw_private_key:604]
82: 22:43:09:000000 tid(0x1428) (H)[ERROR]:OE_ENCLAVE_ABORTING[..\..\host\sgx\calls.c oe_call_enclave_function_by_table_id:857]
 82/106 Test  #82: tests/crypto/enclave ..................................***Failed    0.63 sec
```

**Comment by anitagov** [comment] 2019-06-13 01:46
There were 3 extra bytes between the expected key length of the PEM file and that being read/written to.
The problem is with new openssl version on Windows which generates PEM certificates with CRLF line endings on Windows. Mike's PR #1932 fixes this.

**Comment by anitagov** [comment] 2019-06-13 17:07
@ionutbalutoiu - What was the change made to the Windows CI systems in the past couple of days?

**Comment by anitagov** [comment] 2019-06-13 17:57
Wanted to add that the crypto_crls_cert_chains test also started failing on Windows.

**Comment by ionutbalutoiu** [comment] 2019-06-13 18:32
@anitagov 

Yesterday I run the latest Ansible scripts on top of our 2x live Jenkins Windows servers, but every test would fail due to troubles with Intel SGX (I double checked the `AESMService` service and it was running).

So, I tried to manually revert the changes, and bring the Windows nodes into the previous state:

* I reverted to Intel PSW 2.2 from Intel PSW 2.3 (version 2.3 comes with Ansible right now)
* Uninstalled the `root\SgxLCDevice` and `root\SgxLCDevice_DCAP` drivers

This brought the CI back into the current state, but unfortunately the suites `crypto` and `crypto_crls_cert_chains` started to fail consistently (hence the PR https://github.com/microsoft/openenclave/pull/1926 to temporarily disable them). I'm trying to get these enabled asap!

To avoid any CI blocking this time, I spawned a separate Windows build server, configure it from clean, and try to run only the Windows stages (with the sandbox job) and see if everything works as expected.

[This](https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/OpenEnclave-sandbox/detail/OpenEnclave-sandbox/1498/pipeline) is the most recent sandbox run against the new separate Windows VM configured with Ansible, with Intel PSW 2.3.

The majority of tests fail as such (it errors out when doing `oe_create_enclave`):
```
104: C:/Jenkins/workspace/OpenEnclave-sandbox/build/X64-Debug/tests/pingpong/host/pingpong_host.exe: cannot create enclave: C:/Jenkins/workspace/OpenEnclave-sandbox/build/X64-Debug/tests/pingpong/enc/pingpong_enc
104: 18:15:12:000000 tid(0x149c) (H)[ERROR]:OE_FAILURE[..\..\host\sgx\sgxload.c _get_launch_token:397]
104: 18:15:12:000000 tid(0x149c) (H)[ERROR]:OE_FAILURE[..\..\host\sgx\sgxload.c oe_sgx_initialize_enclave:884]
104: 18:15:12:000000 tid(0x149c) (H)[ERROR]:OE_FAILURE[..\..\host\sgx\create.c oe_sgx_build_enclave:577]
104: 18:15:12:000000 tid(0x149c) (H)[ERROR]:OE_FAILURE[..\..\host\sgx\create.c oe_create_enclave:681]
104/105 Test #104: tests/pingpong ........................................***Failed    0.21 sec
```

Do you have any idea how can I debug this further ?

The `AESMService` seems to be fine:
```
PS C:\Users\oeadmin> Get-Service AESMService

Status   Name               DisplayName
------   ----               -----------
Running  AESMService        Intel® SGX AESM
```

**Comment by ionutbalutoiu** [comment] 2019-06-13 18:42
@anitagov 

Also, I'm aware of the new `openssl` in the CI as noticed by you, https://github.com/microsoft/openenclave/pull/1926#issuecomment-501516179.

My guess would be that, prior running the latest Ansible, the old Git version from the machines had a version of `openssl` correctly generating the PEM certificates, while [Git-2.20.1](https://github.com/microsoft/openenclave/blob/ac841a1d04f0954f110c6ba7742dd289f9569d65/scripts/ansible/roles/windows/openenclave/vars/windows.yml#L24-L26) from latest Ansible has `openssl` that behaves differently.

Anyway, this is only my current assumption, I'll look closely into this as well, once I get past the `oe_create_enclave` errors.

**Comment by anitagov** [comment] 2019-06-13 18:43
John and I looked at the CI failures yesterday and then disabled the 2 failing crypto tests.

Yes, I know the reason for your failure. Intel PSW 2.2 needs to be used with AESM Service due to the issue #1810 
For DCAP libraries, we need Intel PSW 2.3.

We updated the WindowsGettingStarted Guide with this info (part of my PR). Here is the relevant info:
>Intel® SGX Platform Software for Windows (PSW)
The PSW should be installed automatically on Windows 10 with the Fall Creators Update installed, or on a Windows Server 2016 image for an Azure Confidential Compute VM. You can verify that is the case on the command line as follows:

sc query aesmservice
The state of the service should be "running" (4). Follow Intel's documentation for troubleshooting.

Note that Open Enclave is only compatible with the Intel PSW 2.2. To use Intel PSW 2.3 and higher, please refer Building with Intel Data Center Attestation Primitives (DCAP) libraries below.

**Comment by anitagov** [comment] 2019-06-13 18:55
Here is the info from my working ACC Windows VM where the crypto test runs fine. Wondering if you can revert to this version of git.

$git --version
$git version 2.19.1.windows.1

$ openssl
OpenSSL> version
OpenSSL 1.0.2p  14 Aug 2018

------------------------------
On my ACC Windows VM with newer git, the crypto test fails. The versions are:
git 2.21.0.windows.1 and
git version 2.21.0.windows.1

**Comment by ionutbalutoiu** [comment] 2019-06-13 18:57
> John and I looked at the CI failures yesterday and then disabled the 2 failing crypto tests. The newer version of openssl which comes with the newer git causes issues. So, may be good to downgrade git to the previous working version. Sending version info in my next update.
> 
> Yes, I know the reason for your failure. Intel PSW 2.2 needs to be used with AESM Service due to the issue #1810
> For DCAP libraries, we need Intel PSW 2.3.
> 
> We updated the WindowsGettingStarted Guide with this info (part of my PR). Here is the relevant info:
> 
> > Intel® SGX Platform Software for Windows (PSW)
> > The PSW should be installed automatically on Windows 10 with the Fall Creators Update installed, or on a Windows Server 2016 image for an Azure Confidential Compute VM. You can verify that is the case on the command line as follows:
> 
> sc query aesmservice
> The state of the service should be "running" (4). Follow Intel's documentation for troubleshooting.
> 
> Note that Open Enclave is only compatible with the Intel PSW 2.2. To use Intel PSW 2.3 and higher, please refer Building with Intel Data Center Attestation Primitives (DCAP) libraries below.

This makes sense then. Sorry for missing this info from your PR https://github.com/microsoft/openenclave/pull/1865.

I was trying to get the current build servers ready for some sandbox CI runs with the new DCAP libraries Jenkinsfile testing stages.

I assume that there's no way to have 2x versions of Intel PSW installed (as I noticed that version 2.2 gets overwritten once you install 2.3).

In this case, I'll leave this new 3rd Windows CI server solely for the DCAP libraries Jenkins testing stages, and label it differently.

Once I figure out the regression due to the new `openssl` binary, I should be able to re-enable the stages disabled by you and John.

**Comment by ionutbalutoiu** [comment] 2019-06-13 18:58
> Here is the info from my working ACC Windows VM where the crypto test runs fine. Wondering if you can revert to this version of git.
> 
> $git --version
> $git version 2.19.1.windows.1
> 
> $ openssl
> OpenSSL> version
> OpenSSL 1.0.2p 14 Aug 2018
> 
> On my ACC Windows VM with newer git, the crypto test fails. The versions on the failing system are:
> git 2.21.0.windows.1 and
> git version 2.21.0.windows.1

This is valuable information, I'm looking right now for the installer for Git version 2.19.1.

**Comment by anitagov** [comment] 2019-06-13 19:04
Sorry, that I didn't have the correct info for the OpenSSL version on my failing Windows ACC Win VM earlier. Here it is.
OpenSSL 1.1.1a  20 Nov 2018

**Comment by anitagov** [comment] 2019-06-13 19:11
> I assume that there's no way to have 2x versions of Intel PSW installed (as I noticed that version 2.2 gets overwritten once you install 2.3).

I never tried doing this as I have different ACC VMs for AESM and DCAP library. So, this is good info.

> 
> In this case, I'll leave this new 3rd Windows CI server solely for the DCAP libraries Jenkins testing stages, and label it differently.

Yes, sounds good. Also test this new configuration with DCAP libraries and enable it next week only if it works.

> 
> Once I figure out the regression due to the new `openssl` binary, I should be able to re-enable the stages disabled by you and John.

For all the CI Windows systems, the new version of openssl adds CR/LFs to certificates and is causing issues. So, downgrading these will allow us to enable the 2 crypto tests on Windows. Openenclave will need to be enhanced to support the new openssl. We do not have a complete fix yet.

**Comment by ionutbalutoiu** [comment] 2019-06-13 19:16
Just by quickly looking at the `openssl` versions, I notice `1.0.2` vs `1.1.1`.

Going at the [official Win OpenSSL download page](https://slproweb.com/products/Win32OpenSSL.html), I see that they maintain download links for both `1.0.2` and `1.1.1` which makes me think that there's a difference in functionality between these two.

Instead of relying on the `openssl` bundled with Git, what do you think about installing `openssl` separately and add that to the env PATH instead of `C:\Program Files\Git\mingw64\bin` ?

This way, we are not constrained on keeping an older Git, and in the future when  `openssl 1.1.1` is supported, I just bump the installer URL from `1.0.1` to `1.1.1`.

**Comment by ionutbalutoiu** [comment] 2019-06-13 19:21
For now, I'll be downgrading Git, and try to validate that the crypto tests no longer fail with a sandbox run.

**Comment by anitagov** [comment] 2019-06-13 19:36
> Just by quickly looking at the `openssl` versions, I notice `1.0.2` vs `1.1.1`.
> 
> Going at the [official Win OpenSSL download page](https://slproweb.com/products/Win32OpenSSL.html), I see that they maintain download links for both `1.0.2` and `1.1.1` which makes me think that there's a difference in functionality between these two.
> 
> Instead of relying on the `openssl` bundled with Git, what do you think about installing `openssl` separately and add that to the env PATH instead of `C:\Program Files\Git\mingw64\bin` ?
> 
> This way, we are not constrained on keeping an older Git, and in the future when `openssl 1.1.1` is supported, I just bump the installer URL from `1.0.1` to `1.1.1`.
> 
> P.S: I'm ok with downgrading Git as well, I just think that the standalone openssl approach feels cleaner.

For Windows, we seem to be relying on tools that come with git i.e. bash, perl, python and openssl. I like your suggestion of using a separate version of openssl installed. That will allow us to upgrade openssl only when we want to. 
@CodeMonkeyLeet @johnkord - What do you think?

**Comment by ionutbalutoiu** [comment] 2019-06-13 19:43
> For now, I'll be downgrading Git, and try to validate that the crypto tests no longer fail with a sandbox run.

I successfully reverted Git on both our live OE Jenkins systems:
```
PS C:\Users\oeadmin> git version
git version 2.19.1.windows.1

PS C:\Users\oeadmin> openssl version
OpenSSL 1.0.2p  14 Aug 2018
```

I've triggered Bors into PR https://github.com/microsoft/openenclave/pull/1939 (where I re-enable the tests) to see if everything works as expected now.

**Comment by ionutbalutoiu** [comment] 2019-06-13 19:58
> > I assume that there's no way to have 2x versions of Intel PSW installed (as I noticed that version 2.2 gets overwritten once you install 2.3).
> 
> I never tried doing this as I have different ACC VMs for AESM and DCAP library. So, this is good info.
> 

I just opened issue https://github.com/microsoft/openenclave/issues/1940 to follow up later on this matter.

**Comment by ionutbalutoiu** [comment] 2019-06-13 20:16
> I've triggered Bors into PR #1939 (where I re-enable the tests) to see if everything works as expected now.

Bors reported successfully for PR  https://github.com/microsoft/openenclave/pull/1939. Once this gets approved and merged, we'll have `crypto` and `crypto_crls_cert_chains` enabled in CI again.

> For Windows, we seem to be relying on tools that come with git i.e. bash, perl, python and openssl. I like your suggestion of using a separate version of openssl installed. That will allow us to upgrade openssl only when we want to.
> @CodeMonkeyLeet @johnkord - What do you think?

I have opened issue https://github.com/microsoft/openenclave/issues/1941 to continue the discussion on standalone `openssl`. This issue will be closed once PR https://github.com/microsoft/openenclave/pull/1939 is checked in.

**Comment by anitagov** [comment] 2019-06-13 20:44
@ionutbalutoiu - Thanks for filing all the relevant issues.

**Closed** 2019-06-17 17:27 UTC
Labels: ci/cd, testing
