### ISSUE TITLE
Occasionally failing Windows tests due to insufficient enclave size

### ISSUE THREAD

**Issue by aserdean** [Microsoft/openenclave#1476] opened 2019-02-21 09:52 UTC
The following tests fail, although with a low chance:

```
The following tests FAILED:
	 22 - tests/mbed/ecdsa (Failed)
	 23 - tests/mbed/ecp (Failed)
```

Reproduced at:
* [OpenEnclave-sandbox#753](https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/OpenEnclave-sandbox/detail/OpenEnclave-sandbox/753/pipeline/6/#step-24-log-1887)

**Comment by anitagov** [comment] 2019-02-23 01:37
Can you please print the error that occurs using ctest -V? You will need to scroll and find this info in the CI run.

OE_PLATFORM_ERROR (or error 21) can occur as we have very little memory on our ACC Window VMs. We need to move to DC4 systems instead of calling the tests flaky and/or removing them.

**Comment by anitagov** [comment] 2019-02-23 01:39
I looked at the sandbox run and confirmed that both the failures were OE_PLATFORM_ERROR during creation of the enclave.

22/101 Test  #22: tests/mbed/ecdsa ......................................***Failed    0.10 sec

: ..\..\tests\mbed\host\host.c(146): error: oe_create_enclave(): result=21

=== D:/Jenkins/workspace/OpenEnclave-sandbox/build/X64-Release/tests/mbed/host/libmbedtest_host.exe: D:/Jenkins/workspace/OpenEnclave-sandbox/build/X64-Release/tests/mbed/enc/mbedtest_suite_ecdsa

######## data_file: test_suite_ecdsa.data ###### 

###after find_data_file call data_file_name is : test_suite_ecdsa.data

08:43:23:000000 tid(0x6bbc) (H)[ERROR]InitializeEnclave failed (err=0x80) (oe_result_t=OE_PLATFORM_ERROR)[..\..\host\sgx\sgxload.c oe_sgx_initialize_enclave:913]

08:43:23:000000 tid(0x6bbc) (H)[ERROR]:OE_PLATFORM_ERROR[..\..\host\sgx\create.c oe_sgx_build_enclave:681]

08:43:23:000000 tid(0x6bbc) (H)[ERROR]:OE_PLATFORM_ERROR[..\..\host\sgx\create.c oe_create_enclave:790]



        Start  23: tests/mbed/ecp

 23/101 Test  #23: tests/mbed/ecp ........................................***Failed    0.13 sec

: ..\..\tests\mbed\host\host.c(146): error: oe_create_enclave(): result=21

=== D:/Jenkins/workspace/OpenEnclave-sandbox/build/X64-Release/tests/mbed/host/libmbedtest_host.exe: D:/Jenkins/workspace/OpenEnclave-sandbox/build/X64-Release/tests/mbed/enc/mbedtest_suite_ecp

######## data_file: test_suite_ecp.data ###### 

###after find_data_file call data_file_name is : test_suite_ecp.data

08:43:23:000000 tid(0x8340) (H)[ERROR]InitializeEnclave failed (err=0x80) (oe_result_t=OE_PLATFORM_ERROR)[..\..\host\sgx\sgxload.c oe_sgx_initialize_enclave:913]

08:43:23:000000 tid(0x8340) (H)[ERROR]:OE_PLATFORM_ERROR[..\..\host\sgx\create.c oe_sgx_build_enclave:681]

08:43:23:000000 tid(0x8340) (H)[ERROR]:OE_PLATFORM_ERROR[..\..\host\sgx\create.c oe_create_enclave:790]

**Comment by ionutbalutoiu** [comment] 2019-02-25 15:59
> Can you please print the error that occurs using ctest -V? You will need to scroll and find this info in the CI run.
> 
> OE_PLATFORM_ERROR (or error 21) can occur as we have very little memory on our ACC Window VMs. I reduced the enclave size for mbed tests while enabling them but cannot reduce them further as there will a higher test fallout.
> 
> We need to move to DC4 VMs instead of removing these tests. Updated the title to reflect the reason (removed the term flaky).

@aserdean on our side had similar problems with transient failures due to the lack of memory.

I just upgraded the Windows build servers to `Standard_DC4s` size. We're monitoring to see if these popd up again.

**Comment by ionutbalutoiu** [comment] 2019-02-27 11:01
This looks to be fixed once the Windows build servers were upgraded. Closing the issue.

**Closed by ionutbalutoiu** 2019-02-27 11:01 UTC
