### ISSUE TITLE
samples attestation test broken with cmake

### ISSUE THREAD

**Issue by anitagov** [microsoft/openenclave#1715] opened 2019-04-18 02:22 UTC
samples remote attestation fails the second time with the master using ctest and/or cmake.

<build-dir>ctest -R samples ==> will Pass
<build-dir>ctest -R samples ==> Remote attestation Fails due to identity.signer failing

**CI will not catch this as it Passes the first time.** 

This looks like something introduced with adding cmake to samples. However, I am able to get things working after copying samples to another location and using make as instructed in the samples/README.md. **Using cmake results in the same failure in this directory as well.**

**Comment by andschwa** [comment] 2019-04-18 03:34
@anitagov Do you have any other logs from this?

**Comment by anitagov** [comment] 2019-04-18 07:12
[RemoteAttestationFaillog.txt](https://github.com/Microsoft/openenclave/files/3093148/RemoteAttestationFaillog.txt)

**Comment by anitagov** [comment] 2019-04-18 07:13
Attached the logs of the failing samples. Will email you the log with OE_LOG_LEVEL set to VERBOSE.

**Comment by andschwa** [comment] 2019-04-18 17:25
@soccerGB The relevant parts of the log from Anita for you:

```
173: Host: Creating two enclaves
173: Host: Enclave library /openenclave/build/samples/remote_attestation/enclave_a/enclave_a.signed
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/crypto.cpp(76): mbedtls initialized.
173: Host: Enclave successfully created.
173: Host: Enclave library /openenclave/build/samples/remote_attestation/enclave_b/enclave_b.signed
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/crypto.cpp(76): mbedtls initialized.
173: Host: Enclave successfully created.
173: Host: requesting a remote report and the encryption key from 1st enclave
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/enclave_a/ecalls.cpp(43): enter get_remote_report_with_pubkey
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/dispatcher.cpp(96): get_remote_report_with_pubkey
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(59): generate_remote_report succeeded.
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/dispatcher.cpp(133): get_remote_report_with_pubkey succeeded
173: Host: 1st enclave's public key: 
173: -----BEGIN PUBLIC KEY-----
173: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtOI+2gR9X+arUfOesouv
173: Xc7RwrD4+DplGC92uHubfMJo6iWPsD0Ib6unNfOsPzqoTWcX9nWGXMDNk8t46nFm
173: utCecvckqoI3qvCQYfxD3Dnj6rQnta+V+BlKzl6L+3zRQNGBfLAF8I6EIBb6js8q
173: 2ofgfpMfeJPloQBrdj3HEfmN4yOFIDul3ziYRsqRDikD7UUteYF+jGBie0ouDE52
173: wQH3TmrZTlhYnISsi+8VgH902VE4rEbrZcyfQYmKXPei4U5kwWcB2R8J4hx/vK0Y
173: AytcFOonvfMlKu+Dnsj8sMeQvjKUoTBXkCTCFAPm39mJ6T4mv9FuWYMMmGD2IqZu
173: 6wIDAQAB
173: -----END PUBLIC KEY-----
173: Host: requesting 2nd enclave to attest 1st enclave's the remote report and the public key
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(111): identity.signer_id checking failed.
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(113): identity.signer_id Èê}DßÔ³
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(120): m_enclave_mrsigner[0]=0xa1
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(120): m_enclave_mrsigner[1]=0x59
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(120): m_enclave_mrsigner[2]=0xdb
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(120): m_enclave_mrsigner[3]=0xd4
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(120): m_enclave_mrsigner[4]=0xdd
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(120): m_enclave_mrsigner[5]=0xa4
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(120): m_enclave_mrsigner[6]=0x94
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(120): m_enclave_mrsigner[7]=0x22
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(120): m_enclave_mrsigner[8]=0xdf
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(120): m_enclave_mrsigner[9]=0x0
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(120): m_enclave_mrsigner[10]=0x9a
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(120): m_enclave_mrsigner[11]=0x87
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(120): m_enclave_mrsigner[12]=0x6c
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(120): m_enclave_mrsigner[13]=0xc6
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(120): m_enclave_mrsigner[14]=0xa9
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(120): m_enclave_mrsigner[15]=0x3d
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(120): m_enclave_mrsigner[16]=0xc0
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(120): m_enclave_mrsigner[17]=0x43
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(120): m_enclave_mrsigner[18]=0x95
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(120): m_enclave_mrsigner[19]=0x4f
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(120): m_enclave_mrsigner[20]=0x56
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(120): m_enclave_mrsigner[21]=0x78
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(120): m_enclave_mrsigner[22]=0x46
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(120): m_enclave_mrsigner[23]=0xab
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(120): m_enclave_mrsigner[24]=0x4a
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(120): m_enclave_mrsigner[25]=0x52
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(120): m_enclave_mrsigner[26]=0xae
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(120): m_enclave_mrsigner[27]=0xbb
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(120): m_enclave_mrsigner[28]=0xa1
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(120): m_enclave_mrsigner[29]=0x60
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(120): m_enclave_mrsigner[30]=0xd
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(120): m_enclave_mrsigner[31]=0x87
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(123): 
173: 
173: 
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(130): parsedReport.identity.signer_id)[0]=0xc8
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(130): parsedReport.identity.signer_id)[1]=0xea
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(130): parsedReport.identity.signer_id)[2]=0x11
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(130): parsedReport.identity.signer_id)[3]=0x95
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(130): parsedReport.identity.signer_id)[4]=0x7d
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(130): parsedReport.identity.signer_id)[5]=0x2
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(130): parsedReport.identity.signer_id)[6]=0x44
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(130): parsedReport.identity.signer_id)[7]=0xdf
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(130): parsedReport.identity.signer_id)[8]=0x1b
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(130): parsedReport.identity.signer_id)[9]=0xd4
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(130): parsedReport.identity.signer_id)[10]=0x1c
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(130): parsedReport.identity.signer_id)[11]=0xb3
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(130): parsedReport.identity.signer_id)[12]=0x0
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(130): parsedReport.identity.signer_id)[13]=0x7a
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(130): parsedReport.identity.signer_id)[14]=0xd7
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(130): parsedReport.identity.signer_id)[15]=0x9d
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(130): parsedReport.identity.signer_id)[16]=0x5d
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(130): parsedReport.identity.signer_id)[17]=0xea
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(130): parsedReport.identity.signer_id)[18]=0x62
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(130): parsedReport.identity.signer_id)[19]=0xc1
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(130): parsedReport.identity.signer_id)[20]=0x44
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(130): parsedReport.identity.signer_id)[21]=0xee
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(130): parsedReport.identity.signer_id)[22]=0x86
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(130): parsedReport.identity.signer_id)[23]=0x1c
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(130): parsedReport.identity.signer_id)[24]=0x90
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(130): parsedReport.identity.signer_id)[25]=0x5d
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(130): parsedReport.identity.signer_id)[26]=0xa6
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(130): parsedReport.identity.signer_id)[27]=0xbb
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(130): parsedReport.identity.signer_id)[28]=0x71
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(130): parsedReport.identity.signer_id)[29]=0x2b
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(130): parsedReport.identity.signer_id)[30]=0x39
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(130): parsedReport.identity.signer_id)[31]=0x70
173: 
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/attestation.cpp(132): m_enclave_mrsigner ¡YÛÔÝ¤”"ß
173: Enclave: ***/openenclave/build/install/opt/openenclave/share/openenclave/samples/remote_attestation/common/dispatcher.cpp(175): verify_report_and_set_pubkey failed.
173: Host: verify_report_and_set_pubkey failed. OE_OKHost: Terminating enclaves
```

**Comment by andschwa** [comment] 2019-04-18 17:31
Handing this over to you @soccerGB! Maybe something to do with key generation? But I really don't know.

**Comment by andschwa** [comment] 2019-04-18 17:51
@soccerGB Just a guess, but maybe this line:

https://github.com/Microsoft/openenclave/blob/113a8bf22768b3152d57b31085e1cb981556ed99/samples/remote_attestation/enclave_a/CMakeLists.txt#L24

Needs to specify `enclave_a` and `enc.conf` in `DEPENDS` too. I don't know if that's actually what's causing this though.

**Comment by aserdean** [comment] 2019-04-19 09:31
I'll take a look into this one as well.

**Comment by aserdean** [comment] 2019-04-23 15:54
@andschwa I found the issue:

https://github.com/Microsoft/openenclave/blob/master/samples/remote_attestation/Makefile#L21
The second pass is not right because it uses the old `enclave_b_pubkey.h` and `enclave_a_pubkey.h` with the previous public key.

The second issue that comes to mind is that we do not clean the "install_dir". I'm not sure if we want this but I sent also:
https://github.com/aserdean/openenclave/commit/d1c7a9999fe88a1875140d68910a7dfe0002e05b#diff-6ef9161b900632671022358216c7dfe7.

@anitagov can you PTAL at https://github.com/Microsoft/openenclave/pull/1723?

**Comment by anitagov** [comment] 2019-04-23 23:20
Cleaning the install_dir fixed the bug with cmake second PASS.

**Comment by andschwa** [comment] 2019-05-01 22:53
@anitagov and I don't think this is actually fixed. The problem is worked around for the samples test by always cleaning, but this is just a workaround. I'm pretty sure the actual problem is what I stated above with the dependencies. The signed enclave is not recreated if the unsigned enclave is rebuilt. That's my bad from the initial implementation, but let's get it fixed.

**Comment by aserdean** [comment] 2019-05-02 15:43
@andschwa I'm guessing there are two different issues:

> https://github.com/Microsoft/openenclave/blob/master/samples/remote_attestation/Makefile#L21
> The second pass is not right because it uses the old `enclave_b_pubkey.h` and `enclave_a_pubkey.h` with the previous public key.
This was fixed via: https://github.com/Microsoft/openenclave/commit/9959517ac0e9bc3f00f3bac42c1dec40ee4b9162#diff-c3756a26cfeb1e69e8488037402e7693

As per 
> The signed enclave is not recreated if the unsigned enclave is rebuilt.
this is indeed an issue.

I sent out https://github.com/Microsoft/openenclave/pull/1752 just for local_attestation.

I tested it out via:
```
azureuser@aserdean-1804:~/mysamples/local_attestation/build$ make
[  4%] Built target public_key_a
[ 31%] Built target common
[ 45%] Built target enclave_b
[ 54%] Built target enclave_b_signed
[ 59%] Built target public_key_b
[ 72%] Built target enclave_a
[ 81%] Built target enclave_a_signed
[ 81%] Built target sign
[100%] Built target local_attestation_host
azureuser@aserdean-1804:~/mysamples/local_attestation/build$ touch ../localattestation.edl
azureuser@aserdean-1804:~/mysamples/local_attestation/build$ make
[  4%] Built target public_key_a
[  9%] Generating localattestation_t.h, localattestation_t.c, localattestation_args.h
Generating edge routines for the Open Enclave SDK.
Success.
Scanning dependencies of target common
[ 13%] Building C object common/CMakeFiles/common.dir/localattestation_t.c.o
[ 18%] Linking CXX static library libcommon.a
[ 31%] Built target common
[ 36%] Linking CXX executable enclave_b
[ 45%] Built target enclave_b
[ 50%] Generating enclave_b.signed
Created /home/azureuser/mysamples/local_attestation/build/enclave_b/enclave_b.signed
[ 54%] Built target enclave_b_signed
[ 59%] Built target public_key_b
[ 63%] Linking CXX executable enclave_a
[ 72%] Built target enclave_a
[ 77%] Generating enclave_a.signed
Created /home/azureuser/mysamples/local_attestation/build/enclave_a/enclave_a.signed
[ 81%] Built target enclave_a_signed
[ 81%] Built target sign
[ 86%] Generating localattestation_u.h, localattestation_u.c, localattestation_args.h
Generating edge routines for the Open Enclave SDK.
Success.
Scanning dependencies of target local_attestation_host
[ 90%] Building C object host/CMakeFiles/local_attestation_host.dir/localattestation_u.c.o
[ 95%] Linking CXX executable local_attestation_host
[100%] Built target local_attestation_host
azureuser@aserdean-1804:~/mysamples/local_attestation/build$ touch ../enclave_a/ecalls.cpp
azureuser@aserdean-1804:~/mysamples/local_attestation/build$ make
[  4%] Built target public_key_a
[ 31%] Built target common
[ 45%] Built target enclave_b
[ 54%] Built target enclave_b_signed
[ 59%] Built target public_key_b
Scanning dependencies of target enclave_a
[ 63%] Building CXX object enclave_a/CMakeFiles/enclave_a.dir/ecalls.cpp.o
[ 68%] Linking CXX executable enclave_a
[ 72%] Built target enclave_a
[ 77%] Generating enclave_a.signed
Created /home/azureuser/mysamples/local_attestation/build/enclave_a/enclave_a.signed
[ 81%] Built target enclave_a_signed
[ 81%] Built target sign
[100%] Built target local_attestation_host
azureuser@aserdean-1804:~/mysamples/local_attestation/build$ touch ../enclave_b/ecalls.cpp
azureuser@aserdean-1804:~/mysamples/local_attestation/build$ make
[  4%] Built target public_key_a
[ 31%] Built target common
Scanning dependencies of target enclave_b
[ 36%] Building CXX object enclave_b/CMakeFiles/enclave_b.dir/ecalls.cpp.o
[ 40%] Linking CXX executable enclave_b
[ 45%] Built target enclave_b
[ 50%] Generating enclave_b.signed
Created /home/azureuser/mysamples/local_attestation/build/enclave_b/enclave_b.signed
[ 54%] Built target enclave_b_signed
[ 59%] Built target public_key_b
[ 72%] Built target enclave_a
[ 81%] Built target enclave_a_signed
[ 81%] Built target sign
[100%] Built target local_attestation_host
azureuser@aserdean-1804:~/mysamples/local_attestation/build$ touch ../enclave_a/enc.conf
azureuser@aserdean-1804:~/mysamples/local_attestation/build$ make
[  4%] Built target public_key_a
[ 31%] Built target common
[ 45%] Built target enclave_b
[ 54%] Built target enclave_b_signed
[ 59%] Built target public_key_b
[ 72%] Built target enclave_a
[ 77%] Generating enclave_a.signed
Created /home/azureuser/mysamples/local_attestation/build/enclave_a/enclave_a.signed
[ 81%] Built target enclave_a_signed
[ 81%] Built target sign
[100%] Built target local_attestation_host
azureuser@aserdean-1804:~/mysamples/local_attestation/build$ touch ../enclave_b/enc.conf
azureuser@aserdean-1804:~/mysamples/local_attestation/build$ make
[  4%] Built target public_key_a
[ 31%] Built target common
[ 45%] Built target enclave_b
[ 50%] Generating enclave_b.signed
Created /home/azureuser/mysamples/local_attestation/build/enclave_b/enclave_b.signed
[ 54%] Built target enclave_b_signed
[ 59%] Built target public_key_b
[ 72%] Built target enclave_a
[ 81%] Built target enclave_a_signed
[ 81%] Built target sign
[100%] Built target local_attestation_host
azureuser@aserdean-1804:~/mysamples/local_attestation/build$
```
Please let me know if I missed something, so I can add the same for the rest of the samples.

**Comment by aserdean** [comment] 2019-05-09 11:05
Fixed-by: https://github.com/microsoft/openenclave/pull/1752

**Closed by aserdean** 2019-05-09 11:05 UTC
Labels: bug, testing
