### ISSUE TITLE
Flaky libcxx test in CI

### ISSUE THREAD

**Issue by andschwa** [Microsoft/openenclave#1400] opened 2019-01-30 19:27 UTC
I've seen this test occasionally fail in unrelated PRs, making the CI flaky:
```
The following tests FAILED:

	 98 - tests/libcxxtest-std_thread_thread.threads_thread.thread.class_thread.thread.member_detach.pass (Child aborted)
```

**Comment by anitagov** [comment] 2019-01-30 20:22
Yes, I have seen this a few times since the EDL change to libcxx.


Erik: Can you take a look at this failure please as I have not encountered such a failure before?


Andrew: Can you send a link to the CI failure?


- Anita

________________________________

**Comment by andschwa** [comment] 2019-01-30 22:17
Ah! I forgot about that.

[Here's](https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/staging/527/pipeline) a particular run.

That's from PR #1397 which has had it happen to it a couple times.

**Comment by vlaza** [comment] 2019-03-07 19:55
Regarding this issue, we have ran the test 100.000 times in a loop and result was 100% PASS

100% tests passed, 0 tests failed out of 1
Total Test time (real) = 61684.19 sec

I think this can be closed as it cannot be reproduced anymore; please re-evaluate.

@andschwa @anitagov @ionutbalutoiu @johnkord

**Comment by ionutbalutoiu** [comment] 2019-03-07 20:03
We'll reopen if reproduced again. Closing this

**Closed by ionutbalutoiu** 2019-03-07 20:03 UTC
Labels: ci/cd, testing
