### ISSUE TITLE
Issues with container in Jenkins CI

### ISSUE THREAD

**Issue by johnkord** [Microsoft/openenclave#1659] opened 2019-04-02 16:15 UTC
We've hit a few issues with the container stages in Jenkins CI in the last week or so. We're not sure what's going on, but here is example output:

https://oe-jenkins.eastus.cloudapp.azure.com/job/Bors/job/staging/741/display/redirect

**Comment by johnkord** [comment] 2019-04-02 16:16
#1624

**Comment by johnkord** [comment] 2019-04-03 23:13
Here's an example of another weird issue that pops up every so often: https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/staging/755/pipeline

```
At global scope:
cc1plus: error: unrecognized command line option '-Wno-implicit-fallthrough' [-Werror]
cc1plus: all warnings being treated as errors
```

**Comment by ionutbalutoiu** [comment] 2019-04-22 12:57
This issue might be caused by a recently discovered race condition (that got fixed in https://github.com/Microsoft/openenclave/pull/1719).

I'll be monitoring the CI, and if this doesn't reproduce, we can close this issue.

**Comment by ionutbalutoiu** [comment] 2019-04-23 12:01
I have run ~20 sandbox runs only with simulation stages enabled and none gave any error. Seems like https://github.com/Microsoft/openenclave/pull/1719 was the main reason of this failure.

Closing this until further notice.

**Closed by ionutbalutoiu** 2019-04-23 12:01 UTC
Labels: ci/cd
